name: 'robles Upload [STAGING]'
on:
  push:
    branches:
      - 'versions/**'
  workflow_dispatch:

jobs:
  lint:
    name: Lint video course
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint via robles
        uses: docker://razeware/robles:staging
        with:
          entrypoint: '/app/robles/bin/robles'
          args: 'video lint'
        env:
          ENV: staging
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Notify slack - test results
        uses: voxmedia/github-action-slack-notify-build@v1
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel: robles
          status: FAILED
          color: danger

  upload:
    name: Upload to betamax
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Upload via robles
        uses: docker://razeware/robles:staging
        with:
          entrypoint: '/app/robles/bin/robles'
          args: 'video upload'
        env:
          BETAMAX_BASE_URL: https://betamax.rwdev.io:8443
          BETAMAX_SERVICE_API_TOKEN: ${{ secrets.BETAMAX_SERVICE_API_TOKEN_STAGING }}
          ENV: staging
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

